config/routes.rb
Rails.application.routes.draw do
  get '/authors/send_email', to: 'authors#send_email'
  resources :authors, only: [:index, :create] do
    resources :posts, only: [:index]
  end
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home_page#main' # shortcut for the above

  require 'sidekiq/web'
mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :posts, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :author
    before_save :set_is_published
    validates :title, presence: true, length: { minimum: 3 }, if: :publishing?
    validates :body, presence: true
    after_create :send_email

    def set_is_published
        self.is_published = false if self.is_published.nil?
    end

    def publishing?
        return is_published
    end

    def send_email
        NotificationsMailer.post(self).deliver_later
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    Rails.logger.debug "some test"
    @authors = Rails.cache.fetch("all_authors", expires_in: 10.minutes) do
      Author.all
    end
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to authors_path, notice: 'Author was successfully created.' }
        format.js
      else
        format.html { render :new }
        format.js
      end
    end
  end

  def send_email
    render json: {status: Author.all}, status: 50
  end

  def author_params
    params.require(:author).permit(:name, :ph)
  end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def main
    redirect_to :posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    author_id = params[:author_id]
    if author_id.nil?
      @posts = Post.all
    else
      author = Author.find(author_id)
      @posts = author.posts
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @somevariable = "foo"
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    PostsCleanupJob.perform_later if Post.count > 5
    @post = Post.new(post_params)
    @post.author = Author.first
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
        format.js
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :body, :is_published)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :author_name %>
  </div>

  <div class="field">
    <%= form.label :ph %>
    <%= form.text_area :ph, id: :author_ph %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/create.js.erb
var newRow = "<tr><td><%= @author.id %></td><td><%= @author.name %></td><td><%= @author.ph %></td></tr>";
var tbody = $("#authors_list tbody");
tbody.append(newRow);

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table id="authors_list">
  <thead>
    <tr>
    <th>#</th>
      <th>Name</th>
      <th>Ph</th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
      <td><%= author.id %></td>
      <td><%= link_to author.name, author_posts_path(author) %></td>
        <td><%= author.ph %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h1>New Author</h1>

<%= render 'form', author: @author %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

app/views/home_page/foo.html.erb
<h1>Foo</h1>

app/views/home_page/main.html.erb
<h1>This is my new HomePage</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloWorld</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body %>
  </div>

  <div class="field">
    <%= form.label :published? %>
    <%= form.check_box :is_published, id: :post_is_published %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/create.js.erb
alert("<%= @post.errors.count %>");

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Published?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.is_published %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>published?:</strong>
  <%= @post.is_published %>
</p>

<p>
  <strong>some:</strong>
  <%= @somevariable %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>